/** Catálogo de medicamentos comuns para autocomplete no prontuário. */
export const MEDICAMENTOS_CATALOGO: string[] = [
  'Losartana',
  'Enalapril',
  'Captopril',
  'Amlodipina',
  'Hidroclorotiazida',
  'Metformina',
  'Glibenclamida',
  'Insulina NPH',
  'Insulina Regular',
  'Levotiroxina',
  'Omeprazol',
  'Pantoprazol',
  'Ranitidina',
  'Sinvastatina',
  'Atorvastatina',
  'Rosuvastatina',
  'AAS (Ácido Acetilsalicílico)',
  'Clopidogrel',
  'Warfarina',
  'Rivaroxabana',
  'Apixabana',
  'Varfarina',
  'Carvedilol',
  'Propranolol',
  'Atenolol',
  'Metoprolol',
  'Furosemida',
  'Espironolactona',
  'Prednisona',
  'Dexametasona',
  'Salbutamol',
  'Budesonida',
  'Formoterol',
  'Montelucaste',
  'Dipirona',
  'Paracetamol',
  'Ibuprofeno',
  'Naproxeno',
  'Tramadol',
  'Codeína',
  'Gabapentina',
  'Pregabalina',
  'Amitriptilina',
  'Sertralina',
  'Fluoxetina',
  'Escitalopram',
  'Diazepam',
  'Clonazepam',
  'Alprazolam',
  'Zolpidem',
  'Levetiracetam',
  'Carbamazepina',
  'Fenitoína',
  'Valproato de Sódio',
  'Alopurinol',
  'Colchicina',
  'Metotrexato',
  'Hidroxicloroquina',
  'Prednisolona',
  'Cetirizina',
  'Loratadina',
  'Desloratadina',
  'Amoxicilina',
  'Azitromicina',
  'Ciprofloxacino',
  'Metronidazol',
  'Doxazosina',
  'Tamsulosina',
  'Finasterida',
  'Dutasterida',
  'Estradiol',
  'Progesterona',
  'Anticoncepcional Oral',
  'Levonorgestrel',
  'Vitamina D',
  'Vitamina B12',
  'Ferro',
  'Ácido Fólico',
  'Cálcio',
  'Magnésio',
  'Potássio',
  'Bromazepam',
  'Risperidona',
  'Quetiapina',
  'Olanzapina',
  'Haloperidol',
  'Lítio',
  'Donepezila',
  'Memantina',
  'Rivastigmina',
  'Donepezila + Memantina',
  'Nitroglicerina',
  'Isosorbida',
  'Digoxina',
  'Amiodarona',
  'Diltiazem',
  'Verapamil',
  'Nifedipina',
  'Ezetimiba',
  'Fenofibrato',
  'Empagliflozina',
  'Dapagliflozina',
  'Sitagliptina',
  'Vildagliptina',
  'Liraglutida',
  'Semaglutida',
];
