/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/arcada.glb -o components/Odontogram3D.tsx
Author: University of Dundee, School of Dentistry (https://sketchfab.com/DundeeDental)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/permanent-dentition-2f69d7b59c3e4a6a8bcae041bd8e591b
Title: Permanent Dentition
*/

'use client';

import * as THREE from 'three';
import React, { useCallback, useEffect, useMemo } from 'react';
import { ThreeEvent } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { getToothDisplayColor } from '@/lib/odontogram/colors';
import { SEAM_MESHES } from '@/lib/odontogram/meshToFdi';
import { useOdontogramStore } from '@/store/useOdontogramStore';

/** Limpa artefatos comuns do GLB (wireframe, sombras, reflexos agressivos nas frestas). */
function prepareToothMaterial(
  source: THREE.MeshStandardMaterial,
  isSeam = false,
): THREE.MeshStandardMaterial {
  const material = source.clone();
  material.wireframe = false;
  material.flatShading = false;
  material.transparent = false;
  material.opacity = 1;
  material.alphaTest = 0;
  material.side = THREE.FrontSide;
  material.depthTest = true;
  material.polygonOffset = true;
  material.polygonOffsetFactor = isSeam ? 4 : 1;
  material.polygonOffsetUnits = isSeam ? 4 : 1;
  material.depthWrite = !isSeam;
  material.depthFunc = THREE.LessEqualDepth;
  material.roughness = Math.max(material.roughness ?? 0.6, 0.55);
  material.metalness = Math.min(material.metalness ?? 0, 0.05);
  material.envMapIntensity = 0.25;
  return material;
}

type GLTFResult = GLTF & {
  nodes: {
    LL1seam_2ZBrushPolyMesh3D_Mandible_ll1_0: THREE.Mesh;
    LL2seam_2ZBrushPolyMesh3D_Mandible_l2_0: THREE.Mesh;
    LL3seam_2ZBrushPolyMesh3D_Mandible_ll3_0: THREE.Mesh;
    LL4seam_2ZBrushPolyMesh3D_Mandible_ll4_0: THREE.Mesh;
    LL5seam_3ZBrushPolyMesh3D_Mandible_ll5_0: THREE.Mesh;
    LL6seam_2ZBrushPolyMesh3D_Mandible_blinn10_0: THREE.Mesh;
    LL7seam_2ZBrushPolyMesh3D_Mandible_ll7_0: THREE.Mesh;
    LL8seam_2ZBrushPolyMesh3D_Mandible_ll8_0: THREE.Mesh;
    ZBrushPolyMesh3D_Mandible_ll8_0: THREE.Mesh;
    ZBrushPolyMesh3D1_Mandible_ll7_0: THREE.Mesh;
    ZBrushPolyMesh3D2_Mandible_blinn10_0: THREE.Mesh;
    ZBrushPolyMesh3D3_Mandible_ll4_0: THREE.Mesh;
    ZBrushPolyMesh3D4_Mandible_ll5_0: THREE.Mesh;
    ZBrushPolyMesh3D5_Mandible_ll3_0: THREE.Mesh;
    ZBrushPolyMesh3D6_Mandible_l2_0: THREE.Mesh;
    ZBrushPolyMesh3D7_Mandible_ll1_0: THREE.Mesh;
    polySurface1_UL1_0: THREE.Mesh;
    polySurface2_UL1_0: THREE.Mesh;
    polySurface4_blinn14_0: THREE.Mesh;
    polySurface6_blinn15_0: THREE.Mesh;
    polySurface7_blinn18_0: THREE.Mesh;
    polySurface8_blinn18_0: THREE.Mesh;
    ZBrushPolyMesh3D1_blinn14_0: THREE.Mesh;
    polySurface9_blinn19_0: THREE.Mesh;
    polySurface10_blinn19_0: THREE.Mesh;
    ZBrushPolyMesh3D3_blinn16_0: THREE.Mesh;
    ZBrushPolyMesh3D4_blinn17_0: THREE.Mesh;
    ZBrushPolyMesh3D2_blinn15_0: THREE.Mesh;
    ZBrushPolyMesh3D5_blinn18_0: THREE.Mesh;
    ZBrushPolyMesh3D7_blinn20_0: THREE.Mesh;
    ZBrushPolyMesh3D8_blinn16_0: THREE.Mesh;
    ZBrushPolyMesh3D9_blinn17_0: THREE.Mesh;
    polySurface12_blinn20_0: THREE.Mesh;
  };
  materials: {
    Mandible_ll1: THREE.MeshStandardMaterial;
    Mandible_l2: THREE.MeshStandardMaterial;
    Mandible_ll3: THREE.MeshStandardMaterial;
    Mandible_ll4: THREE.MeshStandardMaterial;
    Mandible_ll5: THREE.MeshStandardMaterial;
    Mandible_blinn10: THREE.MeshStandardMaterial;
    Mandible_ll7: THREE.MeshStandardMaterial;
    Mandible_ll8: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    blinn14: THREE.MeshStandardMaterial;
    blinn15: THREE.MeshStandardMaterial;
    blinn18: THREE.MeshStandardMaterial;
    blinn19: THREE.MeshStandardMaterial;
    blinn16: THREE.MeshStandardMaterial;
    blinn17: THREE.MeshStandardMaterial;
    blinn20: THREE.MeshStandardMaterial;
  };
};

interface ToothMeshProps {
  name: string;
  fdi: number;
  geometry: THREE.BufferGeometry;
  sourceMaterial: THREE.MeshStandardMaterial;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
}

function ToothMesh({
  name,
  fdi,
  geometry,
  sourceMaterial,
  position,
  rotation,
  scale,
}: ToothMeshProps) {
  const tooth = useOdontogramStore((state) => state.teeth[fdi]);
  const applyTool = useOdontogramStore((state) => state.applyTool);

  const isSeam = SEAM_MESHES.has(name);
  const meshMaterial = useMemo(
    () => prepareToothMaterial(sourceMaterial, isSeam),
    [sourceMaterial, isSeam],
  );
  const originalHex = useMemo(() => `#${sourceMaterial.color.getHexString()}`, [sourceMaterial]);

  useEffect(() => {
    const displayColor = getToothDisplayColor(tooth, originalHex);
    meshMaterial.color.set(displayColor);
  }, [tooth, meshMaterial, originalHex]);

  const handleClick = useCallback(
    (e: ThreeEvent<MouseEvent>) => {
      e.stopPropagation();
      applyTool(fdi, null);
    },
    [applyTool, fdi],
  );

  const handlePointerOver = useCallback((e: ThreeEvent<PointerEvent>) => {
    e.stopPropagation();
    document.body.style.cursor = 'pointer';
  }, []);

  const handlePointerOut = useCallback(() => {
    document.body.style.cursor = 'auto';
  }, []);

  return (
    <mesh
      name={name}
      geometry={geometry}
      material={meshMaterial}
      position={position}
      rotation={rotation}
      scale={scale}
      renderOrder={isSeam ? 1 : 0}
      castShadow={false}
      receiveShadow={false}
      onClick={handleClick}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
    />
  );
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/arcada.glb') as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.369}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.05, 0.162]} rotation={[-0.023, 0, 0]}>
            <ToothMesh name="LL1seam_2ZBrushPolyMesh3D_Mandible_ll1_0" fdi={41} geometry={nodes.LL1seam_2ZBrushPolyMesh3D_Mandible_ll1_0.geometry} sourceMaterial={materials.Mandible_ll1} position={[-0.027, 0.066, -0.185]} rotation={[-3.09, 0, 0.066]} />
            <ToothMesh name="LL2seam_2ZBrushPolyMesh3D_Mandible_l2_0" fdi={42} geometry={nodes.LL2seam_2ZBrushPolyMesh3D_Mandible_l2_0.geometry} sourceMaterial={materials.Mandible_l2} position={[-0.515, 0.153, -0.129]} rotation={[-3.086, -0.062, 0.069]} />
            <ToothMesh name="LL3seam_2ZBrushPolyMesh3D_Mandible_ll3_0" fdi={43} geometry={nodes.LL3seam_2ZBrushPolyMesh3D_Mandible_ll3_0.geometry} sourceMaterial={materials.Mandible_ll3} position={[0.051, 0.292, 0.043]} rotation={[-3.06, -0.007, 0.025]} />
            <ToothMesh name="LL4seam_2ZBrushPolyMesh3D_Mandible_ll4_0" fdi={44} geometry={nodes.LL4seam_2ZBrushPolyMesh3D_Mandible_ll4_0.geometry} sourceMaterial={materials.Mandible_ll4} position={[0.221, 1.048, -0.153]} rotation={[0.194, -0.018, -0.042]} />
            <ToothMesh name="LL5seam_3ZBrushPolyMesh3D_Mandible_ll5_0" fdi={45} geometry={nodes.LL5seam_3ZBrushPolyMesh3D_Mandible_ll5_0.geometry} sourceMaterial={materials.Mandible_ll5} position={[-0.162, -0.02, 0.09]} rotation={[0.031, 0.023, -0.083]} scale={1.039} />
            <ToothMesh name="LL6seam_2ZBrushPolyMesh3D_Mandible_blinn10_0" fdi={46} geometry={nodes.LL6seam_2ZBrushPolyMesh3D_Mandible_blinn10_0.geometry} sourceMaterial={materials.Mandible_blinn10} position={[0.101, 0.22, 0.163]} rotation={[-3.09, 0, 0.073]} />
            <ToothMesh name="LL7seam_2ZBrushPolyMesh3D_Mandible_ll7_0" fdi={47} geometry={nodes.LL7seam_2ZBrushPolyMesh3D_Mandible_ll7_0.geometry} sourceMaterial={materials.Mandible_ll7} position={[0.976, 0.749, -0.562]} rotation={[-2.925, 0.104, -0.047]} />
            <ToothMesh name="LL8seam_2ZBrushPolyMesh3D_Mandible_ll8_0" fdi={48} geometry={nodes.LL8seam_2ZBrushPolyMesh3D_Mandible_ll8_0.geometry} sourceMaterial={materials.Mandible_ll8} position={[0.535, -0.013, 0.342]} />
            <ToothMesh name="ZBrushPolyMesh3D_Mandible_ll8_0" fdi={38} geometry={nodes.ZBrushPolyMesh3D_Mandible_ll8_0.geometry} sourceMaterial={materials.Mandible_ll8} position={[-6.275, -0.067, 0.07]} rotation={[0.124, 0.087, 0.137]} />
            <ToothMesh name="ZBrushPolyMesh3D1_Mandible_ll7_0" fdi={37} geometry={nodes.ZBrushPolyMesh3D1_Mandible_ll7_0.geometry} sourceMaterial={materials.Mandible_ll7} position={[-7.289, 1.176, 0.568]} rotation={[-2.841, -0.275, 0.115]} />
            <ToothMesh name="ZBrushPolyMesh3D2_Mandible_blinn10_0" fdi={36} geometry={nodes.ZBrushPolyMesh3D2_Mandible_blinn10_0.geometry} sourceMaterial={materials.Mandible_blinn10} position={[-5.142, -0.157, -0.078]} rotation={[-3.091, 0.025, -0.066]} />
            <ToothMesh name="ZBrushPolyMesh3D3_Mandible_ll4_0" fdi={34} geometry={nodes.ZBrushPolyMesh3D3_Mandible_ll4_0.geometry} sourceMaterial={materials.Mandible_ll4} position={[-3.88, 1.147, -0.283]} rotation={[0.194, -0.018, -0.042]} />
            <ToothMesh name="ZBrushPolyMesh3D4_Mandible_ll5_0" fdi={35} geometry={nodes.ZBrushPolyMesh3D4_Mandible_ll5_0.geometry} sourceMaterial={materials.Mandible_ll5} position={[-5.009, 0.42, -0.504]} rotation={[0.118, 0.015, -0.085]} scale={1.069} />
            <ToothMesh name="ZBrushPolyMesh3D5_Mandible_ll3_0" fdi={33} geometry={nodes.ZBrushPolyMesh3D5_Mandible_ll3_0.geometry} sourceMaterial={materials.Mandible_ll3} position={[-2.64, 0.771, -0.148]} rotation={[-2.991, 0.009, -0.067]} />
            <ToothMesh name="ZBrushPolyMesh3D6_Mandible_l2_0" fdi={32} geometry={nodes.ZBrushPolyMesh3D6_Mandible_l2_0.geometry} sourceMaterial={materials.Mandible_l2} position={[-2.628, 0.153, -0.129]} rotation={[-3.086, -0.062, 0.069]} />
            <ToothMesh name="ZBrushPolyMesh3D7_Mandible_ll1_0" fdi={31} geometry={nodes.ZBrushPolyMesh3D7_Mandible_ll1_0.geometry} sourceMaterial={materials.Mandible_ll1} position={[-1.139, 0.066, -0.185]} rotation={[-3.09, 0, 0.066]} />
          </group>
          <group position={[0.588, 0.288, -0.624]} rotation={[0.046, -0.003, -0.009]} scale={1.062}>
            <group position={[-0.128, -0.812, -0.018]} rotation={[3.082, 0, 0]}>
              <ToothMesh name="polySurface1_UL1_0" fdi={11} geometry={nodes.polySurface1_UL1_0.geometry} sourceMaterial={materials.material} position={[-0.273, 0.054, 0.188]} scale={1.025} />
              <ToothMesh name="polySurface2_UL1_0" fdi={21} geometry={nodes.polySurface2_UL1_0.geometry} sourceMaterial={materials.material} position={[-0.231, 0.054, 0.146]} scale={1.025} />
            </group>
            <group position={[-2.241, -0.37, -0.729]} rotation={[0.019, 0.195, -0.099]} scale={1.072}>
              <ToothMesh name="polySurface4_blinn14_0" fdi={14} geometry={nodes.polySurface4_blinn14_0.geometry} sourceMaterial={materials.blinn14} position={[-0.223, -0.298, 0.137]} rotation={[-0.041, -0.015, -0.033]} />
            </group>
            <group position={[-0.962, -1.438, 0.221]} rotation={[3.024, -0.176, -0.158]}>
              <ToothMesh name="polySurface6_blinn15_0" fdi={15} geometry={nodes.polySurface6_blinn15_0.geometry} sourceMaterial={materials.blinn15} position={[-0.115, 0.437, -0.431]} rotation={[-0.064, 0.006, 0.06]} />
            </group>
            <group position={[-0.34, -0.214, -0.464]} rotation={[0.067, 0.077, 0.103]}>
              <ToothMesh name="polySurface7_blinn18_0" fdi={18} geometry={nodes.polySurface7_blinn18_0.geometry} sourceMaterial={materials.blinn18} />
            </group>
            <group position={[-0.526, -0.173, -0.156]} rotation={[0, 0, -0.079]}>
              <ToothMesh name="polySurface9_blinn19_0" fdi={19} geometry={nodes.polySurface9_blinn19_0.geometry} sourceMaterial={materials.blinn19} position={[0, 0.004, 0.094]} />
            </group>
            <group position={[-0.091, -0.66, 0.177]} rotation={[3.083, 0, 0]}>
              <ToothMesh name="polySurface12_blinn20_0" fdi={20} geometry={nodes.polySurface12_blinn20_0.geometry} sourceMaterial={materials.blinn20} position={[-0.109, -0.2, 0.304]} rotation={[0.063, -0.01, 0.016]} />
            </group>
            <ToothMesh name="ZBrushPolyMesh3D1_blinn14_0" fdi={24} geometry={nodes.ZBrushPolyMesh3D1_blinn14_0.geometry} sourceMaterial={materials.blinn14} position={[-2.464, -0.939, -0.312]} rotation={[-0.061, 0.202, -0.083]} scale={1.072} />
            <ToothMesh name="ZBrushPolyMesh3D4_blinn17_0" fdi={17} geometry={nodes.ZBrushPolyMesh3D4_blinn17_0.geometry} sourceMaterial={materials.blinn17} position={[-0.211, 0.514, -0.705]} rotation={[-2.971, -0.07, -0.129]} />
            <ToothMesh name="ZBrushPolyMesh3D2_blinn15_0" fdi={25} geometry={nodes.ZBrushPolyMesh3D2_blinn15_0.geometry} sourceMaterial={materials.blinn15} position={[-1.111, -1.386, 0.312]} rotation={[3.024, -0.176, -0.158]} />
            <ToothMesh name="ZBrushPolyMesh3D5_blinn18_0" fdi={28} geometry={nodes.ZBrushPolyMesh3D5_blinn18_0.geometry} sourceMaterial={materials.blinn18} position={[-0.066, -0.088, -0.463]} rotation={[0.096, 0.075, 0.167]} />
            <ToothMesh name="ZBrushPolyMesh3D7_blinn20_0" fdi={30} geometry={nodes.ZBrushPolyMesh3D7_blinn20_0.geometry} sourceMaterial={materials.blinn20} position={[0.362, -1.153, 0.696]} rotation={[3.002, 0, -0.107]} />
            <ToothMesh name="ZBrushPolyMesh3D9_blinn17_0" fdi={27} geometry={nodes.ZBrushPolyMesh3D9_blinn17_0.geometry} sourceMaterial={materials.blinn17} position={[-4.839, -0.133, -0.764]} rotation={[-3.038, 0.002, -0.179]} />
          </group>
        </group>
      </group>
    </group>
  );
}

export default function Odontogram3D(props: React.ComponentProps<'group'>) {
  return <Model {...props} />;
}

useGLTF.preload('/arcada.glb');
